server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        # Trasa dla user-service – dynamiczne odkrywanie przez Eureka
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/user/**
        # Trasa dla location-service – statyczny adres URL
        - id: location-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/location/**

eureka:
  client:
    enabled: false
  #serviceUrl:
    #  defaultZone: http://localhost:8761/eureka/
  #instance:
  #  prefer-ip-address: true

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG  # Logi dla głównego pakietu gateway
#    reactor.netty: DEBUG                      # Logi dla Netty (silnik sieciowy w gateway)
#    org.springframework.web: DEBUG            # Logi dla warstwy HTTP