server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: favspotuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update #create-drop ==> each time new database
    show-sql: true
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0  # Ustaw 1.0, jeśli chcesz śledzić wszystkie requesty
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans


