server:
  port: 8084

spring:
  application:
    name: location-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/your-realm

  data:
    mongodb:
      uri: mongodb://localhost:27017/locationsdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest  # Domyślny użytkownik w RabbitMQ
    password: guest  # Domyślne hasło w RabbitMQ

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    reactor.core: DEBUG